# The permissions required to use the commands
permission: "ColourNames.Use"
permission-admin: "ColourNames.Admin"

# These are the color codes for the different genders
color-male: "&a"
color-female: "&d"
color-normal: "&7"

# All the messages, you can configure these to whatever you want :)
messages:
    version: "&7You're running &a{0} &7v&a{1}"
    reloaded: "&7The config has been reloaded"
    saved: "&7All player data has been saved to the disk"
    color-code: "{0} &7->&r {1}"
    name-set: "&7Your name has now been set to {0}"
    name-normal: "&7You are now &anormal"
    name-male: "&7You are now &amale"
    name-female: "&7You are now &afemale"
    no-permission: "&cYou don't have permission to do that!"
    invalid-syntax: "&7Error! Incorrect syntax! Example usage: &a/name {0} &7-> {1}"
    usage: "&7Example usage: &a/name {0} &7-> {1}"
    only-one-each: "&cYou can only use one color code and one formatting code"
